// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: otp_emails.sql

package db

import (
	"context"
)

const createOtpEmail = `-- name: CreateOtpEmail :one
INSERT INTO otp_emails (
    username,
    email,
    otp_sent
) VALUES (
     $1, $2, $3
 ) RETURNING id, username, email, otp_sent, total_otp_generations, created_at, expired_at
`

type CreateOtpEmailParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	OtpSent  string `json:"otp_sent"`
}

func (q *Queries) CreateOtpEmail(ctx context.Context, arg CreateOtpEmailParams) (OtpEmail, error) {
	row := q.db.QueryRowContext(ctx, createOtpEmail, arg.Username, arg.Email, arg.OtpSent)
	var i OtpEmail
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.OtpSent,
		&i.TotalOtpGenerations,
		&i.CreatedAt,
		&i.ExpiredAt,
	)
	return i, err
}
