# This openai key should not be exposed like this and should be made available using appropriate tools
# This is a dummy key generated by a dummy openai account.
APIKEY = "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"