name : Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code into the Go Module directory
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Docker and Docker Compose on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_SSH_KEY }}
          script: |
            # Install Docker if not installed
            if ! type docker >/dev/null 2>&1; then
                sudo yum update -y
                sudo yum -y install docker
                sudo service docker start
            fi
            
            # Install Docker Compose if not installed
            if ! type docker-compose >/dev/null 2>&1; then
                sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
                sudo chmod +x /usr/local/bin/docker-compose
            fi

      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_SSH_KEY }}
          script: |
            #!/bin/bash
            # Path to ec2-init.sh
            chmod +x /home/ec2-user/simplebank/.github/workflows/ec2-init.sh
            /home/ec2-user/simplebank/.github/workflows/ec2-init.sh

