name: Deploy to Production

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code into the Go Module directory
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: kanishkmittal55/simple-bank-backend:latest
          build-args: |
            DB_URL=${{ secrets.DB_URL }}
            REDIS_URL=${{ secrets.REDIS_URL }}
